//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKIN
    {
        public decimal MACHECKIN { get; set; }
        public decimal MAKH { get; set; }
        public System.DateTime THOIGIANVAO { get; set; }
        public Nullable<System.DateTime> THOIGIANRA { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
