//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKYGOITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANGKYGOITAP()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public decimal MADKGT { get; set; }
        public decimal MAKH { get; set; }
        public decimal MAGOITAP { get; set; }
        public System.DateTime NGAYDANGKY { get; set; }
        public System.DateTime NGAYBATDAU { get; set; }
        public System.DateTime NGAYKETTHUC { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual GOITAP GOITAP { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
