//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIACHI
    {
        public decimal MADC { get; set; }
        public decimal MAKH { get; set; }
        public string TINHTHANHPHO { get; set; }
        public string QUANHUYEN { get; set; }
        public string PHUONGXA { get; set; }
        public string DIACHICUTHE { get; set; }
        public Nullable<bool> LADIACHIMACDINH { get; set; }
        public System.DateTime NGAYTHEM { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
