//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHLOP
    {
        public decimal MALICHLOP { get; set; }
        public decimal MALOP { get; set; }
        public decimal MANV { get; set; }
        public System.DateTime NGAYHOC { get; set; }
        public System.DateTime GIOBATDAU { get; set; }
        public System.DateTime GIOKETTHUC { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual LOPHOC LOPHOC { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
