//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHTAPPT
    {
        public decimal MALICHPT { get; set; }
        public decimal MADKPT { get; set; }
        public System.DateTime NGAYTAP { get; set; }
        public System.DateTime GIOBATDAU { get; set; }
        public System.DateTime GIOKETTHUC { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual DANGKYPT DANGKYPT { get; set; }
    }
}
