//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_PHONGGYM : DbContext
    {
        public QL_PHONGGYM()
            : base("name=QL_PHONGGYM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHECKIN> CHECKINs { get; set; }
        public virtual DbSet<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        public virtual DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<CHUYENMON> CHUYENMONs { get; set; }
        public virtual DbSet<DANGKYGOITAP> DANGKYGOITAPs { get; set; }
        public virtual DbSet<DANGKYLOP> DANGKYLOPs { get; set; }
        public virtual DbSet<DANGKYPT> DANGKYPTs { get; set; }
        public virtual DbSet<DIACHI> DIACHIs { get; set; }
        public virtual DbSet<GOITAP> GOITAPs { get; set; }
        public virtual DbSet<HINHANH> HINHANHs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LICHLOP> LICHLOPs { get; set; }
        public virtual DbSet<LICHTAPPT> LICHTAPPTs { get; set; }
        public virtual DbSet<LOAIKHACHHANG> LOAIKHACHHANGs { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<LOPHOC> LOPHOCs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
    
        public virtual int P_DECRYPTADDCIPHER(string sTR, Nullable<decimal> k, ObjectParameter rESULT)
        {
            var sTRParameter = sTR != null ?
                new ObjectParameter("STR", sTR) :
                new ObjectParameter("STR", typeof(string));
    
            var kParameter = k.HasValue ?
                new ObjectParameter("K", k) :
                new ObjectParameter("K", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DECRYPTADDCIPHER", sTRParameter, kParameter, rESULT);
        }
    
        public virtual int P_DECRYPTMULCIPHER(string sTR, Nullable<decimal> k, ObjectParameter rESULT)
        {
            var sTRParameter = sTR != null ?
                new ObjectParameter("STR", sTR) :
                new ObjectParameter("STR", typeof(string));
    
            var kParameter = k.HasValue ?
                new ObjectParameter("K", k) :
                new ObjectParameter("K", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DECRYPTMULCIPHER", sTRParameter, kParameter, rESULT);
        }
    
        public virtual int P_ENCRYPTADDCIPHER(string sTR, Nullable<decimal> k, ObjectParameter rESULT)
        {
            var sTRParameter = sTR != null ?
                new ObjectParameter("STR", sTR) :
                new ObjectParameter("STR", typeof(string));
    
            var kParameter = k.HasValue ?
                new ObjectParameter("K", k) :
                new ObjectParameter("K", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_ENCRYPTADDCIPHER", sTRParameter, kParameter, rESULT);
        }
    
        public virtual int P_ENCRYPTMULCIPHER(string sTR, Nullable<decimal> k, ObjectParameter rESULT)
        {
            var sTRParameter = sTR != null ?
                new ObjectParameter("STR", sTR) :
                new ObjectParameter("STR", typeof(string));
    
            var kParameter = k.HasValue ?
                new ObjectParameter("K", k) :
                new ObjectParameter("K", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_ENCRYPTMULCIPHER", sTRParameter, kParameter, rESULT);
        }
    
        public virtual int SP_DANGKYTAPTHU(string p_TENKH, string p_SDT, string p_EMAIL)
        {
            var p_TENKHParameter = p_TENKH != null ?
                new ObjectParameter("P_TENKH", p_TENKH) :
                new ObjectParameter("P_TENKH", typeof(string));
    
            var p_SDTParameter = p_SDT != null ?
                new ObjectParameter("P_SDT", p_SDT) :
                new ObjectParameter("P_SDT", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DANGKYTAPTHU", p_TENKHParameter, p_SDTParameter, p_EMAILParameter);
        }
    
        public virtual int SP_KHACHHANGDANGKY(string p_TENKH, string p_GIOITINH, Nullable<System.DateTime> p_NGAYSINH, string p_SDT, string p_EMAIL, string p_TENDANGNHAP, string p_MATKHAU)
        {
            var p_TENKHParameter = p_TENKH != null ?
                new ObjectParameter("P_TENKH", p_TENKH) :
                new ObjectParameter("P_TENKH", typeof(string));
    
            var p_GIOITINHParameter = p_GIOITINH != null ?
                new ObjectParameter("P_GIOITINH", p_GIOITINH) :
                new ObjectParameter("P_GIOITINH", typeof(string));
    
            var p_NGAYSINHParameter = p_NGAYSINH.HasValue ?
                new ObjectParameter("P_NGAYSINH", p_NGAYSINH) :
                new ObjectParameter("P_NGAYSINH", typeof(System.DateTime));
    
            var p_SDTParameter = p_SDT != null ?
                new ObjectParameter("P_SDT", p_SDT) :
                new ObjectParameter("P_SDT", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_TENDANGNHAPParameter = p_TENDANGNHAP != null ?
                new ObjectParameter("P_TENDANGNHAP", p_TENDANGNHAP) :
                new ObjectParameter("P_TENDANGNHAP", typeof(string));
    
            var p_MATKHAUParameter = p_MATKHAU != null ?
                new ObjectParameter("P_MATKHAU", p_MATKHAU) :
                new ObjectParameter("P_MATKHAU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHACHHANGDANGKY", p_TENKHParameter, p_GIOITINHParameter, p_NGAYSINHParameter, p_SDTParameter, p_EMAILParameter, p_TENDANGNHAPParameter, p_MATKHAUParameter);
        }
    
        public virtual int SP_KHACHHANGLOGIN(string p_TENDANGNHAP, string p_MATKHAU)
        {
            var p_TENDANGNHAPParameter = p_TENDANGNHAP != null ?
                new ObjectParameter("P_TENDANGNHAP", p_TENDANGNHAP) :
                new ObjectParameter("P_TENDANGNHAP", typeof(string));
    
            var p_MATKHAUParameter = p_MATKHAU != null ?
                new ObjectParameter("P_MATKHAU", p_MATKHAU) :
                new ObjectParameter("P_MATKHAU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHACHHANGLOGIN", p_TENDANGNHAPParameter, p_MATKHAUParameter);
        }
    }
}
