//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public decimal MACTHD { get; set; }
        public decimal MAHD { get; set; }
        public Nullable<decimal> MADKGT { get; set; }
        public Nullable<decimal> MADKPT { get; set; }
        public Nullable<decimal> MADKLOP { get; set; }
        public Nullable<decimal> MASP { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public decimal DONGIA { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual DANGKYGOITAP DANGKYGOITAP { get; set; }
        public virtual DANGKYLOP DANGKYLOP { get; set; }
        public virtual DANGKYPT DANGKYPT { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
