//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETGIOHANG
    {
        public decimal MACHITIETGH { get; set; }
        public decimal MAKH { get; set; }
        public Nullable<decimal> MASP { get; set; }
        public Nullable<decimal> MAGOITAP { get; set; }
        public Nullable<decimal> MALOP { get; set; }
        public decimal SOLUONG { get; set; }
        public decimal DONGIA { get; set; }
        public System.DateTime NGAYTHEM { get; set; }
    
        public virtual GOITAP GOITAP { get; set; }
        public virtual LOPHOC LOPHOC { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
