//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKYPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANGKYPT()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.LICHTAPPTs = new HashSet<LICHTAPPT>();
        }
    
        public decimal MADKPT { get; set; }
        public decimal MAKH { get; set; }
        public decimal MANV { get; set; }
        public decimal SOBUOI { get; set; }
        public decimal GIAMOIBUOI { get; set; }
        public System.DateTime NGAYDANGKY { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHTAPPT> LICHTAPPTs { get; set; }
    }
}
