//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETGIOHANGs = new HashSet<CHITIETGIOHANG>();
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.HINHANHs = new HashSet<HINHANH>();
        }
    
        public decimal MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> MALOAISP { get; set; }
        public decimal DONGIA { get; set; }
        public decimal SOLUONGTON { get; set; }
        public Nullable<decimal> GIAKHUYENMAI { get; set; }
        public string HANG { get; set; }
        public string XUATXU { get; set; }
        public string BAOHANH { get; set; }
        public string MOTACHUNG { get; set; }
        public string MOTACHITIET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANH> HINHANHs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
